<?php
$URL = $_SERVER["HTTP_HOST"] . $_SERVER["REQUEST_URI"];
$NAME = $_SERVER["SCRIPT_NAME"];
$PORT = $_SERVER["SERVER_PORT"];
$PROTOCOLO = $_SERVER["SERVER_PROTOCOL"];

echo "HOST - {$URL}<br>NAME - {$NAME}<br> PORT - {$PORT}<br> PROTOLOCO - {$PROTOCOLO}"
?>